jaka_Robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J1
    pid: {p: 200.0, i: 1.0, d: 10.0, i_clamp: 100}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J2
    pid: {p: 350.0, i: 5.0, d: 10.0, i_clamp: 100}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: J3
    pid: {p: 200.0, i: 2.0, d: 10.0, i_clamp: 100}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: J4
    pid: {p: 200.0, i: 1.0, d: 10.0, i_clamp: 100}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: J5
    pid: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 100}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: J6
    pid: {p: 50.0, i: 0.1, d: 10.0, i_clamp: 100}

  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: J1
    pid: {p: 5.0, i: 0.1, d: 10.0}

  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: J2
    pid: {p: 5.0, i: 0.1, d: 10.0}

  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: J3
    pid: {p: 5.0, i: 0.1, d: 10.0}

  joint4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: J4
    pid: {p: 5.0, i: 0.1, d: 10.0}

  joint5_effort_controller:
    type: effort_controllers/JointEffortController
    joint: J5
    pid: {p: 5.0, i: 0.1, d: 10.0}

  joint6_effort_controller:
    type: effort_controllers/JointEffortController
    joint: J6
    pid: {p: 5.0, i: 0.1, d: 10.0}

